name: CI Workflow

on:
  push:
    branches: [main]
    paths:
      - "**"
  pull_request:
    branches: [main]
    paths:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      # - name: Run tests
      #   run: cargo test --verbose
      #   env:
      #     MONGO_URI: ${{secrets.MONGO_URI}}
      #     MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
      #     API_KEY: ${{secrets.API_KEY}}